package com.draponquest;

import javafx.scene.Scene;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyEvent;

/**
 * Handles keyboard input for DraponQuest JavaFX.
 * Replaces the DoJa key event system with modern JavaFX input handling.
 *
 * @author Yakkun (Original key event system concept)
 * @author Modern Migration
 */
public class GameInputHandler {
    
    /**
     * The main game instance that this input handler interacts with.
     */
    private final DraponQuestFX game;
    /**
     * Flag to prevent multiple rapid key presses from being registered.
     */
    private boolean isHit = false; // Prevents double key presses
    
    /**
     * Constructs a GameInputHandler for the given game instance and scene.
     * It attaches key pressed and key released event handlers to the scene.
     * @param game The DraponQuestFX game instance to send input events to.
     * @param scene The JavaFX Scene object to which the input handlers will be attached.
     */
    public GameInputHandler(DraponQuestFX game, Scene scene) {
        this.game = game;
        scene.setOnKeyPressed(this::handleKeyPressed);
        scene.setOnKeyReleased(this::handleKeyReleased);
    }
    
    /**
     * Handles key press events, preventing rapid multiple presses for most keys
     * and routing the input to the appropriate game logic based on the current game mode.
     * Special keys like ESCAPE, ENTER, and SPACE are always processed.
     * @param event The JavaFX KeyEvent generated by the key press.
     */
    public void handleKeyPressed(KeyEvent event) {
        // Always allow ESC and ENTER to work
        if (event.getCode() == KeyCode.ESCAPE) {
            game.hitSoft2();
            return;
        }
        if (event.getCode() == KeyCode.ENTER || event.getCode() == KeyCode.SPACE) {
            game.hitKeySelect();
            return;
        }
        // Prevent double key presses for other keys
        if (isHit) {
            return;
        }
        isHit = true;
        // Battle mode input
        if (game.currentMode == DraponQuestFX.MODE_BATTLE) {
            game.battleManager.handleBattleInput(event.getCode());
            return;
        }

        // Shop mode input
        if (game.currentMode == DraponQuestFX.MODE_SHOP) {
            game.handleShopInput(event.getCode());
            return;
        }

        // Inventory mode input
        if (game.currentMode == DraponQuestFX.MODE_INVENTORY) {
            game.handleInventoryInput(event.getCode());
            return;
        }


        switch (event.getCode()) {
            case UP:
            case W:
                game.hitUp();
                break;
            case DOWN:
            case S:
                game.hitDown();
                break;
            case LEFT:
            case A:
                game.hitLeft();
                break;
            case RIGHT:
            case D:
                game.hitRight();
                break;
            case F5:
                game.saveGame();
                break;
            case F9:
                game.loadGame();
                break;
            case M:
                // Toggle music on/off
                game.toggleMusic();
                break;
            case T:
                // Toggle sound effects on/off
                game.toggleSound();
                break;
            case L:
                // Toggle language (English/Japanese)
                game.toggleLanguage();
                break;
            case OPEN_BRACKET:
                // Decrease volume
                game.decreaseVolume();
                break;
            case CLOSE_BRACKET:
                // Increase volume
                game.increaseVolume();
                break;
            default:
                // Ignore other keys
                break;
        }
    }
    
    /**
     * Handles key release events, primarily used to reset the internal 'hit' flag
     * to allow subsequent key presses to be registered.
     * @param event The JavaFX KeyEvent generated by the key release.
     */
    public void handleKeyReleased(KeyEvent event) {
        // Reset hit flag when key is released
        isHit = false;
    }
} 